title: Calvin Chen Homepage
page-top-title: Calvin Chen Homepage
top-section-bg-text: A Dedicated CV, Image Editing & LLMs System Nerd Dreaming of AGI World
home-subtitle: Calvin Chen
copyright-text: '&copy; Calvin Chen 2024. All Rights Reserved. Template by Calvin Chen From <a href="https://github.com/Calvin11311/Calvin11311.github.io">This Repo</a>.'
